<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-08-21 22:59

$extensionClassesPath = t3lib_extMgm::extPath('dynamic_sitemap') . 'Classes/';
return array(
	'tx_dynamicsitemap_view_sitemap_index' => $extensionClassesPath . 'View/Sitemap/Index.php',
	'tx_dynamicsitemap_controller_sitemapcontroller' => $extensionClassesPath . 'Controller/SitemapController.php',
);
?>